routes/web.php
<?php

use App\Http\Controllers\{
    AkunController,
    BatalOrderController,
    BillOfMaterialController,
    BukuBesarController,
    DashboardController,
    DivisiController,
    JabatanController,
    JurnalController,
    LaporanKeuanganController,
    OtorisasiController,
    PasswordController,
    PelangganController,
    PemesananMaterialController,
    PenerimaanMaterialController,
    ProdukController,
    ProfileController,
    SalesOrderController,
    SupplierController,
    SuratJalanController,
    SuratPerintahKerjaController,
    UserController,
    NotaPelunasanSupplierController,
    NotaPembayaranController,
    PerkiraanHppController,
    PermintaanMaterialController,
    RealisasiProduksiController,
};
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'verify'   => false,
]);

Route::middleware('auth')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])
        ->name('dashboard');

    Route::post('markNotification', [DashboardController::class, 'markNotification'])
        ->name('markNotification');

    Route::resource('divisis', DivisiController::class)
        ->except(['show']);

    Route::resource('jabatans', JabatanController::class)
        ->except('show');

    Route::resource('users', UserController::class)
        ->except(['show', 'destroy']);

    Route::resource('pelanggans', PelangganController::class)
        ->except(['show']);

    Route::resource('suppliers', SupplierController::class)
        ->except(['show']);

    Route::get('otorisasis', [OtorisasiController::class, 'index'])
        ->name('otorisasis.index');

    Route::resource('produks', ProdukController::class)
        ->except(['show', 'destroy']);

    Route::get('akuns', [AkunController::class, 'index'])
        ->name('akuns.index');

    Route::prefix('profile')->group(function () {
        Route::get('/{user}', [ProfileController::class, 'edit'])
            ->name('profile.edit');

        Route::patch('/{user}', [ProfileController::class, 'update'])
            ->name('profile.update');

        Route::patch('/passwordUpdate/{user}', [PasswordController::class, 'update'])
            ->name('password.update');
    });

    Route::patch('salesOrders/{salesOrder}/confirm', [SalesOrderController::class, 'confirm'])
        ->name('salesOrders.confirm');

    Route::resource('salesOrders', SalesOrderController::class);

    Route::post('batalOrders/{salesOrder}', [BatalOrderController::class, 'store'])
            ->name('batalOrders.store');

    Route::resource('batalOrders', BatalOrderController::class)
        ->except(['create', 'store', 'show', 'destroy']);

    Route::post('notaPembayarans/{salesOrder}', [NotaPembayaranController::class, 'store'])
        ->name('notaPembayarans.store');

    Route::resource('notaPembayarans', NotaPembayaranController::class)
        ->except(['create', 'store']);

    Route::get('suratJalans/create/{salesOrder}', [SuratJalanController::class, 'create'])
        ->name('suratJalans.create');

    Route::post('suratJalans/{salesOrder}', [SuratJalanController::class, 'store'])
        ->name('suratJalans.store');

    Route::resource('suratJalans', SuratJalanController::class)
        ->except(['create', 'store']);

    Route::patch('pemesananMaterials/confirm/{pemesananMaterial}', [PemesananMaterialController::class, 'confirm'])
        ->name('pemesananMaterials.confirm');

    Route::patch('pemesananMaterials/open/{pemesananMaterial}', [PemesananMaterialController::class, 'open'])
        ->name('pemesananMaterials.open');

    Route::resource('pemesananMaterials', PemesananMaterialController::class);

    Route::get('penerimaanMaterials/create/{pemesananMaterial}', [PenerimaanMaterialController::class, 'create'])
        ->name('penerimaanMaterials.create');

    Route::post('penerimaanMaterials/store/{pemesananMaterial}', [PenerimaanMaterialController::class, 'store'])
        ->name('penerimaanMaterials.store');

    Route::resource('penerimaanMaterials', PenerimaanMaterialController::class)
        ->except(['create', 'store']);

    Route::post('notaPelunasanSuppliers/store/{pemesananMaterial}', [NotaPelunasanSupplierController::class, 'store'])
        ->name('notaPelunasanSuppliers.store');

    Route::resource('notaPelunasanSuppliers', NotaPelunasanSupplierController::class)
        ->except(['create', 'store']);

    Route::resource('billOfMaterials', BillOfMaterialController::class);

    Route::resource('suratPerintahKerjas', SuratPerintahKerjaController::class);

    Route::get('permintaanMaterials/getBillOfMaterials/{id}', [PermintaanMaterialController::class, 'getBillOfMaterials']);

    Route::patch('permintaanMaterials/confirm/{permintaanMaterial}', [PermintaanMaterialController::class, 'confirm'])
        ->name('permintaanMaterials.confirm');
    
    Route::resource('permintaanMaterials', PermintaanMaterialController::class)
        ->except(['edit', 'update']);

    Route::get('perkiraanHpps/create/{billOfMaterial}', [PerkiraanHppController::class, 'create'])
        ->name('perkiraanHpps.create');

    Route::post('perkiraanHpps/store/{billOfMaterial}', [PerkiraanHppController::class, 'store'])
        ->name('perkiraanHpps.store');

    Route::resource('perkiraanHpps', PerkiraanHppController::class)
        ->except(['create', 'store']);

    Route::resource('realisasiProduksis', RealisasiProduksiController::class);

    Route::post('jurnals/find', [JurnalController::class, 'find'])
        ->name('jurnals.find');

    Route::get('jurnals/close', [JurnalController::class, 'close'])
        ->name('jurnals.close');

    Route::resource('jurnals', JurnalController::class)
        ->only(['index', 'create', 'store']);

    Route::get('bukuBesars', [BukuBesarController::class, 'index'])
        ->name('bukuBesars.index');

    Route::post('bukuBesars/find', [BukuBesarController::class, 'find'])
        ->name('bukuBesars.find');

    Route::get('laporanKeuangans', [LaporanKeuanganController::class, 'index'])
        ->name('laporanKeuangans.index');

    Route::post('laporanKeuangans/find', [LaporanKeuanganController::class, 'find'])
        ->name('laporanKeuangans.find');
});

app/Models/Jabatan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Jabatan extends Model
{
    use HasFactory;

    protected $fillable = [
        'nama_jabatan',
    ];

    public function users()
    {
        return $this->hasMany(User::class);
    }

    public function otorisasis()
    {
        return $this->belongsToMany(Otorisasi::class);
    }
}

app/Http/Controllers/JabatanController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreJabatanRequest;
use App\Http\Requests\UpdateJabatanRequest;
use App\Models\Jabatan;
use App\Models\Otorisasi;
use Illuminate\Support\Facades\Gate;

class JabatanController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('jabatan access'), 403);

        $jabatans = Jabatan::with(['otorisasis'])->get();

        return view('jabatan.index', compact('jabatans'));
    }

    public function create()
    {
        abort_if(Gate::denies('jabatan create'), 403);

        $otorisasis = Otorisasi::all(['id', 'nama_otorisasi']);

        return view('jabatan.create', compact('otorisasis'));
    }

    public function store(StoreJabatanRequest $request)
    {
        $jabatan = Jabatan::create($request->validated());

        $jabatan->otorisasis()->attach($request->input('otorisasi_ids'));

        return redirect()
            ->route('jabatans.index')
            ->with('success', 'Data jabatan berhasil disimpan!');
    }

    public function edit(Jabatan $jabatan)
    {
        abort_if(Gate::denies('jabatan edit'), 403);

        $otorisasis = Otorisasi::all(['id', 'nama_otorisasi']);
        
        $jabatan->load(['otorisasis']);

        return view('jabatan.edit', compact('jabatan', 'otorisasis'));
    }

    public function update(UpdateJabatanRequest $request, Jabatan $jabatan)
    {
        $jabatan->update($request->validated());
        
        $jabatan->otorisasis()->sync($request->input('otorisasi_ids'));

        return redirect()
            ->route('jabatans.index')
            ->with('success', 'Data jabatan berhasil diubah!');
    }

    public function destroy(Jabatan $jabatan)
    {
        abort_if(Gate::denies('jabatan delete'), 403);

        if ($jabatan->users()->exists()) {
            return redirect()
                ->route('jabatans.index')
                ->with('error', 'Data jabatan gagal dihapus!');
        }

        $jabatan->otorisasis()->detach();
        
        $jabatan->delete();

        return redirect()
            ->route('jabatans.index')
            ->with('success', 'Data jabatan berhasil dihapus!');
    }
}

resources/views/jabatan/create.blade.php
@extends('layouts.app')

@section('vendor css')
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/forms/select/select2.min.css') }}">
@endsection

@section('breadcrumb')
<div class="content-header-left col-12 mb-2 mt-1">
    <div class="breadcrumbs-top">
        <h5 class="content-header-title float-left pr-1 mb-0">Buat Jabatan</h5>
        <div class="breadcrumb-wrapper d-none d-sm-block">
            <ol class="breadcrumb p-0 mb-0 pl-1">
                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}"><i class="bx bx-home-alt"></i></a>
                </li>
                <li class="breadcrumb-item active">Jabatan
                </li>
            </ol>
        </div>
    </div>
</div>
@endsection

@section('content')
<section id="basic-vertical-layouts">
    <div class="row match-height">
        <div class="col-md-6 col-12">
            <div class="card">
                <form class="form form-vertical" action="{{ route('jabatans.store') }}" method="post">
                    @csrf
                    
                    <div class="card-body">
                        <div class="form-body">
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group">
                                        <label>Nama Jabatan</label>
                                        <input type="text" aria-describedby="namaHelp" class="form-control @error('nama_jabatan') is-invalid @enderror" name="nama_jabatan" placeholder="Masukan Nama Jabatan" value="{{ old('nama_jabatan') }}">

                                        @error('nama_jabatan')
                                            <small id="namaHelp" class="form-text text-danger">{{ $message}}</small>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <label>Otorisasi Jabatan</label>
                                        <select aria-describedby="otorisasiHelp" class="select2 form-control" name="otorisasi_ids[]" multiple="multiple">
                                            @foreach($otorisasis as $otorisasi)
                                                <option value="{{ $otorisasi->id }}" {{ (in_array($otorisasi->id, old('otorisasi_ids', []))) ? 'selected' : '' }}>{{ $otorisasi->nama_otorisasi }}</option>
                                            @endforeach
                                        </select>

                                        @error('otorisasi_ids')
                                            <small id="otorisasiHelp" class="form-text text-danger">{{ $message}}</small>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row ">
                            <div class="col-6">
                                <button type="reset" class="btn btn-light-secondary">Reset</button>
                            </div>
                            <div class="col-6 d-flex justify-content-end">
                                <button type="submit" class="btn btn-primary">Simpan Data</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
@endsection

@section('page vendor js')
<script src="{{ asset('app-assets/vendors/js/forms/select/select2.full.min.js') }}"></script>
@endsection

@section('page js')
<script src="{{ asset('app-assets/js/scripts/forms/select/form-select2.js') }}"></script>
@endsection

resources/views/jabatan/edit.blade.php
@extends('layouts.app')

@section('vendor css')
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/forms/select/select2.min.css') }}">
@endsection

@section('breadcrumb')
<div class="content-header-left col-12 mb-2 mt-1">
    <div class="breadcrumbs-top">
        <h5 class="content-header-title float-left pr-1 mb-0">Ubah Jabatan</h5>
        <div class="breadcrumb-wrapper d-none d-sm-block">
            <ol class="breadcrumb p-0 mb-0 pl-1">
                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}"><i class="bx bx-home-alt"></i></a>
                </li>
                <li class="breadcrumb-item active">Jabatan
                </li>
            </ol>
        </div>
    </div>
</div>
@endsection

@section('content')
<section id="basic-vertical-layouts">
    <div class="row match-height">
        <div class="col-md-6 col-12">
            <div class="card">
                <form class="form form-vertical" action="{{ route('jabatans.update', $jabatan) }}" method="post">
                    @csrf
                    @method('patch')

                    <div class="card-body">
                        <div class="form-body">
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group">
                                        <label>Nama Jabatan</label>
                                        <input type="text" aria-describedby="namaHelp" class="form-control @error('nama_jabatan') is-invalid @enderror" name="nama_jabatan" placeholder="Masukan Nama Jabatan" value="{{ old('nama_jabatan', $jabatan->nama_jabatan) }}">

                                        @error('nama_jabatan')
                                            <small id="namaHelp" class="form-text text-danger">{{ $message}}</small>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <label>Otorisasi Jabatan</label>
                                        <select aria-describedby="otorisasiHelp" class="select2 form-control" name="otorisasi_ids[]" multiple="multiple">
                                            @foreach($otorisasis as $otorisasi)
                                                <option value="{{ $otorisasi->id }}" {{ (in_array($otorisasi->id, old('otorisasi_ids', [])) || $jabatan->otorisasis->contains($otorisasi->id)) ? 'selected' : '' }}>{{ $otorisasi->nama_otorisasi }}</option>
                                            @endforeach
                                        </select>

                                        @error('otorisasi_ids')
                                            <small id="otorisasiHelp" class="form-text text-danger">{{ $message}}</small>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row ">
                            <div class="col-6">
                                <button type="reset" class="btn btn-light-secondary">Reset</button>
                            </div>
                            <div class="col-6 d-flex justify-content-end">
                                <button type="submit" class="btn btn-warning">Ubah Data</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
@endsection

@section('page vendor js')
<script src="{{ asset('app-assets/vendors/js/forms/select/select2.full.min.js') }}"></script>
@endsection

@section('page js')
<script src="{{ asset('app-assets/js/scripts/forms/select/form-select2.js') }}"></script>
@endsection

resources/views/jabatan/index.blade.php
@extends('layouts.app')

@section('vendor css')
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/tables/datatable/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/tables/datatable/responsive.bootstrap4.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/tables/datatable/buttons.bootstrap4.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/extensions/toastr.css') }}">
@endsection

@section('page css')
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/plugins/extensions/toastr.css') }}">
@endsection

@section('breadcrumb')
<div class="content-header-left col-12 mb-2 mt-1">
    <div class="breadcrumbs-top">
        <h5 class="content-header-title float-left pr-1 mb-0">Jabatan</h5>
        <div class="breadcrumb-wrapper d-none d-sm-block">
            <ol class="breadcrumb p-0 mb-0 pl-1">
                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}"><i class="bx bx-home-alt"></i></a>
                </li>
                <li class="breadcrumb-item active">Jabatan
                </li>
            </ol>
        </div>
    </div>
</div>
@endsection

@section('content')
<section id="basic-datatable">
    @can('jabatan create')
        <div class="invoice-create-btn mb-1">
            <a href="{{ route('jabatans.create') }}" class="btn btn-primary btn-sm round glow align-items-center">Buat Jabatan</a>
        </div>
    @endcan
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body card-dashboard">
                    <div class="table-responsive">
                        <table class="table zero-configuration">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>nama jabatan</th>
                                    <th>daftar otorisasi</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($jabatans as $jabatan)
                                    <tr>
                                        <td>
                                            <small class="text-muted">{{ $loop->index +1 }}</small>
                                        </td>
                                        <td>
                                            <small class="text-muted">{{ $jabatan->nama_jabatan }}</small>
                                            </td>
                                        <td>
                                            <ul>
                                                @foreach ($jabatan->otorisasis as $otorisasi)
                                                    <li style="display:inline">
                                                        <span class="badge badge-light-secondary badge-pill mb-1">{{ $otorisasi->nama_otorisasi }}</span>
                                                    </li>
                                                @endforeach    
                                            </ul>    
                                        </td>
                                        <td>
                                            <div class="invoice-action">
                                                @can('jabatan edit')
                                                    <a href="{{ route('jabatans.edit', $jabatan) }}" class="invoice-action-edit mr-1">
                                                        <i class="bx bx-edit-alt"></i>
                                                    </a>
                                                @endcan

                                                @can('jabatan delete')
                                                    <a href="#DeleteModal{{ $loop->index }}" data-toggle="modal" class="invoice-action-delete cursor-pointer">
                                                        <i class="bx bx-trash-alt"></i>
                                                    </a>
                                                @endcan
                                            </div>
                                        </td>
                                    </tr>

                                    {{-- BEGIN DELETE MODAL --}}
                                    <div class="modal fade text-left" id="DeleteModal{{ $loop->index }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel160" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                                            <div class="modal-content">
                                                <div class="modal-header bg-danger">
                                                    <h5 class="modal-title white" id="myModalLabel160">Hapus Data Jabatan</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <i class="bx bx-x"></i>
                                                    </button>
                                                </div>
                                                <form action="{{ route('jabatans.destroy', $jabatan) }}" method="post">
                                                    @csrf
                                                    @method('delete')

                                                    <div class="modal-body">
                                                        <p>Apakah anda yakin untuk menghapus data tersebut?</p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-light-secondary" data-dismiss="modal">
                                                            <i class="bx bx-x d-block d-sm-none"></i>
                                                            <span class="d-none d-sm-block">Batal</span>
                                                        </button>
                                                        <button type="submit" class="btn btn-danger ml-1">
                                                            <i class="bx bx-check d-block d-sm-none"></i>
                                                            <span class="d-none d-sm-block">Hapus Data</span>
                                                        </button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                    {{-- END DELETE MODAL --}}
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@section('page vendor js')
<script src="{{ asset('app-assets/vendors/js/tables/datatable/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/tables/datatable/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/tables/datatable/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/tables/datatable/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/extensions/toastr.min.js') }}"></script>
@endsection

@section('page js')
<script src="{{ asset('app-assets/js/scripts/datatables/datatable.js') }}"></script>
@endsection

@section('script')
<script type="text/javascript">
    @if(Session::has('success'))
        toastr['success']("{{ session('success') }}", {
            tapToDismiss: true,
        });
    @endif

    @if(Session::has('error'))
        toastr['error']("{{ session('error') }}", {
            tapToDismiss: true,
        });
    @endif
</script>
@endsection