routes/web.php
<?php

use App\Http\Controllers\{
    AkunController,
    BatalOrderController,
    BillOfMaterialController,
    BukuBesarController,
    DashboardController,
    DivisiController,
    JabatanController,
    JurnalController,
    LaporanKeuanganController,
    OtorisasiController,
    PasswordController,
    PelangganController,
    PemesananMaterialController,
    PenerimaanMaterialController,
    ProdukController,
    ProfileController,
    SalesOrderController,
    SupplierController,
    SuratJalanController,
    SuratPerintahKerjaController,
    UserController,
    NotaPelunasanSupplierController,
    NotaPembayaranController,
    PerkiraanHppController,
    PermintaanMaterialController,
    RealisasiProduksiController,
};
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'verify'   => false,
]);

Route::middleware('auth')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])
        ->name('dashboard');

    Route::post('markNotification', [DashboardController::class, 'markNotification'])
        ->name('markNotification');

    Route::resource('divisis', DivisiController::class)
        ->except(['show']);

    Route::resource('jabatans', JabatanController::class)
        ->except('show');

    Route::resource('users', UserController::class)
        ->except(['show', 'destroy']);

    Route::resource('pelanggans', PelangganController::class)
        ->except(['show']);

    Route::resource('suppliers', SupplierController::class)
        ->except(['show']);

    Route::get('otorisasis', [OtorisasiController::class, 'index'])
        ->name('otorisasis.index');

    Route::resource('produks', ProdukController::class)
        ->except(['show', 'destroy']);

    Route::get('akuns', [AkunController::class, 'index'])
        ->name('akuns.index');

    Route::prefix('profile')->group(function () {
        Route::get('/{user}', [ProfileController::class, 'edit'])
            ->name('profile.edit');

        Route::patch('/{user}', [ProfileController::class, 'update'])
            ->name('profile.update');

        Route::patch('/passwordUpdate/{user}', [PasswordController::class, 'update'])
            ->name('password.update');
    });

    Route::patch('salesOrders/{salesOrder}/confirm', [SalesOrderController::class, 'confirm'])
        ->name('salesOrders.confirm');

    Route::resource('salesOrders', SalesOrderController::class);

    Route::post('batalOrders/{salesOrder}', [BatalOrderController::class, 'store'])
            ->name('batalOrders.store');

    Route::resource('batalOrders', BatalOrderController::class)
        ->except(['create', 'store', 'show', 'destroy']);

    Route::post('notaPembayarans/{salesOrder}', [NotaPembayaranController::class, 'store'])
        ->name('notaPembayarans.store');

    Route::resource('notaPembayarans', NotaPembayaranController::class)
        ->except(['create', 'store']);

    Route::get('suratJalans/create/{salesOrder}', [SuratJalanController::class, 'create'])
        ->name('suratJalans.create');

    Route::post('suratJalans/{salesOrder}', [SuratJalanController::class, 'store'])
        ->name('suratJalans.store');

    Route::resource('suratJalans', SuratJalanController::class)
        ->except(['create', 'store']);

    Route::patch('pemesananMaterials/confirm/{pemesananMaterial}', [PemesananMaterialController::class, 'confirm'])
        ->name('pemesananMaterials.confirm');

    Route::patch('pemesananMaterials/open/{pemesananMaterial}', [PemesananMaterialController::class, 'open'])
        ->name('pemesananMaterials.open');

    Route::resource('pemesananMaterials', PemesananMaterialController::class);

    Route::get('penerimaanMaterials/create/{pemesananMaterial}', [PenerimaanMaterialController::class, 'create'])
        ->name('penerimaanMaterials.create');

    Route::post('penerimaanMaterials/store/{pemesananMaterial}', [PenerimaanMaterialController::class, 'store'])
        ->name('penerimaanMaterials.store');

    Route::resource('penerimaanMaterials', PenerimaanMaterialController::class)
        ->except(['create', 'store']);

    Route::post('notaPelunasanSuppliers/store/{pemesananMaterial}', [NotaPelunasanSupplierController::class, 'store'])
        ->name('notaPelunasanSuppliers.store');

    Route::resource('notaPelunasanSuppliers', NotaPelunasanSupplierController::class)
        ->except(['create', 'store']);

    Route::resource('billOfMaterials', BillOfMaterialController::class);

    Route::resource('suratPerintahKerjas', SuratPerintahKerjaController::class);

    Route::get('permintaanMaterials/getBillOfMaterials/{id}', [PermintaanMaterialController::class, 'getBillOfMaterials']);

    Route::patch('permintaanMaterials/confirm/{permintaanMaterial}', [PermintaanMaterialController::class, 'confirm'])
        ->name('permintaanMaterials.confirm');
    
    Route::resource('permintaanMaterials', PermintaanMaterialController::class)
        ->except(['edit', 'update']);

    Route::get('perkiraanHpps/create/{billOfMaterial}', [PerkiraanHppController::class, 'create'])
        ->name('perkiraanHpps.create');

    Route::post('perkiraanHpps/store/{billOfMaterial}', [PerkiraanHppController::class, 'store'])
        ->name('perkiraanHpps.store');

    Route::resource('perkiraanHpps', PerkiraanHppController::class)
        ->except(['create', 'store']);

    Route::resource('realisasiProduksis', RealisasiProduksiController::class);

    Route::post('jurnals/find', [JurnalController::class, 'find'])
        ->name('jurnals.find');

    Route::get('jurnals/close', [JurnalController::class, 'close'])
        ->name('jurnals.close');

    Route::resource('jurnals', JurnalController::class)
        ->only(['index', 'create', 'store']);

    Route::get('bukuBesars', [BukuBesarController::class, 'index'])
        ->name('bukuBesars.index');

    Route::post('bukuBesars/find', [BukuBesarController::class, 'find'])
        ->name('bukuBesars.find');

    Route::get('laporanKeuangans', [LaporanKeuanganController::class, 'index'])
        ->name('laporanKeuangans.index');

    Route::post('laporanKeuangans/find', [LaporanKeuanganController::class, 'find'])
        ->name('laporanKeuangans.find');
});

app/Models/NotaPelunasanSupplier.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class NotaPelunasanSupplier extends Model
{
    use HasFactory;

    protected $fillable = [
        'no_nota',
        'cara_bayar',
        'nominal_pelunasan',
        'keterangan',
        'user_id',
        'pemesanan_material_id'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function pemesananMaterial()
    {
        return $this->belongsTo(PemesananMaterial::class);
    }
}

app/Models/SalesOrder.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class  SalesOrder extends Model
{
    use HasFactory;

    protected $fillable = [
        'no_nota',
        'tanggal_kirim',
        'tanggal_jatuh_tempo',
        'total',
        'diskon',
        'keterangan',
        'status_nota',
        'status_pembayaran',
        'user_id',
        'pelanggan_id',
    ];

    public function produks()
    {
        return $this->belongsToMany(Produk::class)
            ->using(ProdukSalesOrder::class)
            ->withPivot(['id', 'kuantitas', 'harga', 'status_order']);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function pelanggan()
    {
        return $this->belongsTo(Pelanggan::class);
    }

    public function batalOrder()
    {
        return $this->hasOne(BatalOrder::class);
    }

    public function notaPembayarans()
    {
        return $this->hasMany(NotaPembayaran::class);
    }

    public function suratJalans()
    {
        return $this->hasMany(SuratJalan::class);
    }

    public function getGrandTotalAttribute()
    {
        return ($this->total - $this->diskon);
    }

    public function getNominalBayarAttribute()
    {
        return $this->notapembayarans->sum('nominal_bayar');
    }

    public function getUnShippedProductAttribute()
    {
        return $this->produks()
            ->wherePivotIn('status_order', ['done', 'partially shipped'])
            ->count();
    }

    public function scopeConfirmed($query)
    {
        return $query->where('status_nota', 'confirmed');
    }
}

app/Http/Controllers/NotaPelunasanSupplierController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreNotaPelunasanSupplierRequest;
use App\Http\Requests\UpdateNotaPelunasanSupplierRequest;
use App\Models\NotaPelunasanSupplier;
use App\Models\PemesananMaterial;
use App\Services\NotaPelunasanSupplierService;
use Illuminate\Support\Facades\Gate;

class NotaPelunasanSupplierController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('notaPelunasanSupplier access'), 403);

        $notaPelunasanSuppliers = NotaPelunasanSupplier::with(['user', 'pemesananMaterial.supplier'])
            ->get();

        return view('notaPelunasanSupplier.index', compact('notaPelunasanSuppliers'));
    }

    public function store(StoreNotaPelunasanSupplierRequest $request, PemesananMaterial $pemesananMaterial, NotaPelunasanSupplierService $service)
    {
        $notaPelunasanSupplier = $service->handleStoreNotaPelunasanSupplier(
            $request->validated(), 
            auth()->id(), 
            $pemesananMaterial->id
        );

        return redirect()
            ->route('notaPelunasanSuppliers.show', $notaPelunasanSupplier)
            ->with('success', 'Nota pelunasan supplier berhasil disimpan!');
    }

    public function show(NotaPelunasanSupplier $notaPelunasanSupplier)
    {
        $notaPelunasanSupplier->load(['pemesananMaterial.supplier', 'user.jabatan']);

        return view('notaPelunasanSupplier.detail', compact('notaPelunasanSupplier'));
    }

    public function edit(NotaPelunasanSupplier $notaPelunasanSupplier)
    {
        abort_if(Gate::denies('notaPelunasanSupplier edit'), 403);

        $notaPelunasanSupplier->load(['pemesananMaterial']);
        
        return view('notaPelunasanSupplier.edit', compact('notaPelunasanSupplier'));
    }

    public function update(UpdateNotaPelunasanSupplierRequest $request, NotaPelunasanSupplier $notaPelunasanSupplier, NotaPelunasanSupplierService $service)
    {
        $notaPelunasanSupplier = $service->handleUpdateNotaPelunasanSupplier(
            $request->validated(), 
            $notaPelunasanSupplier->id
        );

        return redirect()
            ->route('notaPelunasanSuppliers.show', $notaPelunasanSupplier)
            ->with('success', 'Nota pelunasan supplier berhasil diubah!');
    }

    public function destroy(NotaPelunasanSupplier $notaPelunasanSupplier, NotaPelunasanSupplierService $service)
    {
        abort_if(Gate::denies('notaPelunasanSupplier delete'), 403);

        $notaPelunasanSupplier = $service->handleDestroyNotaPelunasanSupplier($notaPelunasanSupplier->id);

        return redirect()
            ->route('notaPelunasanSuppliers.index')
            ->with('success', 'Nota pelunasan supplier berhasil dihapus!');
    }
}

resources/views/notapelunasansupplier/detail.blade.php
@extends('layouts.app')

@section('vendor css')
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/extensions/toastr.css') }}">
@endsection

@section('page css')
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/plugins/extensions/toastr.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/pages/app-invoice.css') }}">
@endsection

@section('breadcrumb')
<div class="content-header-left col-12 mb-2 mt-1">
    <div class="breadcrumbs-top">
        <h5 class="content-header-title float-left pr-1 mb-0">Detail Nota Pelunasan Supplier</h5>
        <div class="breadcrumb-wrapper d-none d-sm-block">
            <ol class="breadcrumb p-0 mb-0 pl-1">
                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}"><i class="bx bx-home-alt"></i></a>
                </li>
                <li class="breadcrumb-item active">Nota Pelunasan Supplier
                </li>
            </ol>
        </div>
    </div>
</div>
@endsection

@section('content')
<section class="invoice-view-wrapper">
    <div class="row">
        <!-- invoice view page -->
        <div class="col-xl-6 col-md-12 col-12">
            <div class="card invoice-print-area">
                <div class="card-body pb-0 mx-25">
                    <!-- header section -->
                    <div class="row">
                        <div class="col-lg-4 col-md-12">
                            <span class="invoice-number mr-50">{{ $notaPelunasanSupplier->no_nota }}</span>
                        </div>
                        <div class="col-lg-8 col-md-12">
                            <div class="d-flex align-items-center justify-content-lg-end flex-wrap">
                                <div>
                                    <small class="text-muted">Tanggal Pelunasan:</small>
                                    <span>@datetime($notaPelunasanSupplier->created_at)</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <!-- invoice address and contact -->
                    <div class="row invoice-info">
                        <div class="col-sm-6 col-12 mt-1">
                            <h6 class="invoice-from">Data Supplier</h6>
                            <div class="mb-1">
                                <span>{{ $notaPelunasanSupplier->pemesananMaterial->supplier->nama_supplier }}</span>
                            </div>
                            <div class="mb-1">
                                <span>{{ $notaPelunasanSupplier->pemesananMaterial->supplier->alamat_supplier }}, {{ $notaPelunasanSupplier->pemesananMaterial->supplier->kota_supplier }}</span>
                            </div>
                            <div class="mb-1">
                                <span>{{ $notaPelunasanSupplier->pemesananMaterial->supplier->no_telepon }}</span>
                            </div>
                        </div>
                        <div class="col-sm-6 col-12 mt-1">
                            <h6 class="invoice-from">Data Karyawan</h6>
                            <div class="mb-1">
                                <span>{{ $notaPelunasanSupplier->user->nama_karyawan }}</span>
                            </div>
                            <div class="mb-1">
                                <span>{{ $notaPelunasanSupplier->user->jabatan->nama_jabatan }}</span>
                            </div>
                        </div>
                    </div>
                    <hr>
                </div>
                <!-- product details table-->
                <div class="invoice-product-details table-responsive">
                    <table class="table table-borderless mb-0">
                        <thead>
                            <tr class="border-0">
                                <th scope="col">Nomor Pemesanan Material</th>
                                <th scope="col">Keterangan</th>
                                <th scope="col">Cara Pembayaran</th>
                                <th scope="col" class="text-right">Nominal</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <a href="{{ route('pemesananMaterials.show', $notaPelunasanSupplier->pemesanan_material_id) }}">{{ $notaPelunasanSupplier->pemesananMaterial->no_nota }}</a>
                                </td>
                                <td>
                                    @switch($notaPelunasanSupplier->keterangan)
                                        @case(null)
                                            <small class="text-muted">-</small>
                                            @break
                                        @default
                                            <small class="text-muted">{{ $notaPelunasanSupplier->keterangan }}</small>
                                    @endswitch
                                </td>
                                <td>
                                    <small class="text-muted">{{ $notaPelunasanSupplier->cara_bayar }}</small>
                                </td>
                                <td class="text-right">
                                    <small class="text-muted">@money($notaPelunasanSupplier->nominal_pelunasan)</small>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-6">
                            @can('notaPelunasanSupplier edit')
                                <a href="{{ route('notaPelunasanSuppliers.edit', $notaPelunasanSupplier) }}" class="btn btn-warning">Ubah Data</a>
                            @endcan
                        </div>
                        <div class="col-6 d-flex justify-content-end">
                            @can('notaPelunasanSupplier delete')
                                <a href="#DeleteModal" class="btn btn-danger" data-toggle="modal">Hapus Data</a>
                            @endcan
                        </div>                        

                        {{-- BEGIN DELETE MODAL --}}
                        <div class="modal fade text-left" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel160" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                                <div class="modal-content">
                                    <div class="modal-header bg-danger">
                                        <h5 class="modal-title white" id="myModalLabel160">Hapus Nota Pelunasan Supplier</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <i class="bx bx-x"></i>
                                        </button>
                                    </div>
                                    <form action="{{ route('notaPelunasanSuppliers.destroy', $notaPelunasanSupplier) }}" method="post">
                                        @csrf
                                        @method('delete')

                                        <div class="modal-body">
                                            <p>Apakah anda yakin untuk menghapus transaksi tersebut?</p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-light-secondary" data-dismiss="modal">
                                                <i class="bx bx-x d-block d-sm-none"></i>
                                                <span class="d-none d-sm-block">Batal</span>
                                            </button>
                                            <button type="submit" class="btn btn-danger ml-1">
                                                <i class="bx bx-check d-block d-sm-none"></i>
                                                <span class="d-none d-sm-block">Hapus Data</span>
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        {{-- END DELETE MODAL --}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@section('page vendor js')
<script src="{{ asset('app-assets/vendors/js/extensions/toastr.min.js') }}"></script>
@endsection

@section('script')
<script type="text/javascript">
    @if(Session::has('success'))
        toastr['success']("{{ session('success') }}", {
            tapToDismiss: true,
        });
    @endif
</script>
@endsection

resources/views/notapelunasansupplier/edit.blade.php
@extends('layouts.app')

@section('breadcrumb')
<div class="content-header-left col-12 mb-2 mt-1">
    <div class="breadcrumbs-top">
        <h5 class="content-header-title float-left pr-1 mb-0">Ubah Nota Pelunasan Supplier</h5>
        <div class="breadcrumb-wrapper d-none d-sm-block">
            <ol class="breadcrumb p-0 mb-0 pl-1">
                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}"><i class="bx bx-home-alt"></i></a>
                </li>
                <li class="breadcrumb-item active">Nota Pelunasan Supplier
                </li>
            </ol>
        </div>
    </div>
</div>
@endsection

@section('content')
<section id="basic-vertical-layouts">
    <div class="row match-height">
        <div class="col-md-6 col-12">
            <div class="card">
                <form class="form form-vertical" action="{{ route('notaPelunasanSuppliers.update', $notaPelunasanSupplier) }}" method="post">
                    @csrf
                    @method('patch')

                    <div class="card-body">                        
                        <div class="form-body">
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group">
                                        <label>Nomor Nota</label>
                                        <input type="text" class="form-control" value="{{ $notaPelunasanSupplier->no_nota }}" readonly>
                                    </div>
                                    <div class="form-group">
                                        <label>Nomor Nota Permintaan Material</label>
                                        <input type="text" class="form-control" value="{{ $notaPelunasanSupplier->pemesananMaterial->no_nota }}" readonly>
                                    </div>
                                    <div class="form-group">
                                        <label>Nominal Pembelian</label>
                                        <input data-inputmask="
                                            'alias': 'currency', 
                                            'prefix': 'Rp ',
                                            'placeholder': 'Rp 0',
                                            'rightAlign': 'true',
                                            'autoUnmask': 'true',
                                            'allowMinus': 'false',
                                            'removeMaskOnSubmit': 'true',
                                            'digits': '0'" 
                                            class="form-control" value="{{ $notaPelunasanSupplier->pemesananMaterial->grand_total }}" readonly>
                                    </div>
                                    <div class="form-group">
                                        <label>Sisa Tagihan</label>
                                        <input data-inputmask="
                                            'alias': 'currency', 
                                            'prefix': 'Rp ',
                                            'placeholder': 'Rp 0',
                                            'rightAlign': 'true',
                                            'autoUnmask': 'true',
                                            'allowMinus': 'false',
                                            'removeMaskOnSubmit': 'true',
                                            'digits': '0'" 
                                            class="form-control" value="{{ $notaPelunasanSupplier->pemesananMaterial->grand_total - $notaPelunasanSupplier->pemesananMaterial->nominal_pelunasan }}" readonly>
                                    </div>
                                    <div class="form-group mb-0">
                                        <label>Cara Pembayaran</label>
                                        <select aria-describedby="caraBayarHelp" class="form-control" name="cara_bayar">
                                            <option hidden>Pilih Cara Pembayaran</option>
                                            <option value="Tunai" {{ old('cara_bayar', $notaPelunasanSupplier->cara_bayar) == 'Tunai' ? 'selected' : '' }}>Tunai</option>
                                            <option value="Transfer" {{ old('cara_bayar', $notaPelunasanSupplier->cara_bayar) == 'Transfer' ? 'selected' : '' }}>Transfer</option>
                                        </select>

                                        @error('cara_bayar')
                                            <small id="caraBayarHelp" class="form-text text-danger">{{ $message }}</small>
                                        @enderror
                                    </div>
                                    <div class="form-group mb-0">
                                        <label>Nominal Pelunasan</label>
                                        <input data-inputmask="
                                            'alias': 'currency', 
                                            'prefix': 'Rp ',
                                            'placeholder': 'Rp 0',
                                            'rightAlign': 'true',
                                            'autoUnmask': 'true',
                                            'allowMinus': 'false',
                                            'removeMaskOnSubmit': 'true',
                                            'digits': '0', 
                                            'max': {{ $notaPelunasanSupplier->nominal_pelunasan + $notaPelunasanSupplier->pemesananMaterial->grand_total - $notaPelunasanSupplier->pemesananMaterial->nominal_pelunasan }}" 
                                            aria-describedby="nominalPelunasanHelp" class="form-control @error('nominal_pelunasan') is-invalid @enderror" name="nominal_pelunasan" value="{{ old('nominal_pelunasan', $notaPelunasanSupplier->nominal_pelunasan) }}">

                                        @error('nominal_pelunasan')
                                            <small id="nominalPelunasanHelp" class="form-text text-danger">{{ $message }}</small>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label>Keterangan</label>
                                        <textarea class="form-control" name="keterangan" cols="30" rows="5">{{ old('keterangan', $notaPelunasanSupplier->keterangan) }}</textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row ">
                            <div class="col-6">
                                <button type="reset" class="btn btn-light-secondary">Reset</button>
                            </div>
                            <div class="col-6 d-flex justify-content-end">
                                <button type="submit" class="btn btn-warning">Ubah Data</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
@endsection

@section('page vendor js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.6/jquery.inputmask.min.js" 
    integrity="sha512-6Jym48dWwVjfmvB0Hu3/4jn4TODd6uvkxdi9GNbBHwZ4nGcRxJUCaTkL3pVY6XUQABqFo3T58EMXFQztbjvAFQ==" 
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.6/bindings/inputmask.binding.js" 
    integrity="sha512-J6WEJE0No+5Qqm9/T93q88yRQjvoAioXG4gzJ+eqZtLi+ZBgimZDkTiLWiljwrwnoQw+xwECQm282RJ6CrJnlw==" 
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
@endsection