routes/web.php
<?php

use App\Http\Controllers\{
    AkunController,
    BatalOrderController,
    BillOfMaterialController,
    BukuBesarController,
    DashboardController,
    DivisiController,
    JabatanController,
    JurnalController,
    LaporanKeuanganController,
    OtorisasiController,
    PasswordController,
    PelangganController,
    PemesananMaterialController,
    PenerimaanMaterialController,
    ProdukController,
    ProfileController,
    SalesOrderController,
    SupplierController,
    SuratJalanController,
    SuratPerintahKerjaController,
    UserController,
    NotaPelunasanSupplierController,
    NotaPembayaranController,
    PerkiraanHppController,
    PermintaanMaterialController,
    RealisasiProduksiController,
};
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'verify'   => false,
]);

Route::middleware('auth')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])
        ->name('dashboard');

    Route::post('markNotification', [DashboardController::class, 'markNotification'])
        ->name('markNotification');

    Route::resource('divisis', DivisiController::class)
        ->except(['show']);

    Route::resource('jabatans', JabatanController::class)
        ->except('show');

    Route::resource('users', UserController::class)
        ->except(['show', 'destroy']);

    Route::resource('pelanggans', PelangganController::class)
        ->except(['show']);

    Route::resource('suppliers', SupplierController::class)
        ->except(['show']);

    Route::get('otorisasis', [OtorisasiController::class, 'index'])
        ->name('otorisasis.index');

    Route::resource('produks', ProdukController::class)
        ->except(['show', 'destroy']);

    Route::get('akuns', [AkunController::class, 'index'])
        ->name('akuns.index');

    Route::prefix('profile')->group(function () {
        Route::get('/{user}', [ProfileController::class, 'edit'])
            ->name('profile.edit');

        Route::patch('/{user}', [ProfileController::class, 'update'])
            ->name('profile.update');

        Route::patch('/passwordUpdate/{user}', [PasswordController::class, 'update'])
            ->name('password.update');
    });

    Route::patch('salesOrders/{salesOrder}/confirm', [SalesOrderController::class, 'confirm'])
        ->name('salesOrders.confirm');

    Route::resource('salesOrders', SalesOrderController::class);

    Route::post('batalOrders/{salesOrder}', [BatalOrderController::class, 'store'])
            ->name('batalOrders.store');

    Route::resource('batalOrders', BatalOrderController::class)
        ->except(['create', 'store', 'show', 'destroy']);

    Route::post('notaPembayarans/{salesOrder}', [NotaPembayaranController::class, 'store'])
        ->name('notaPembayarans.store');

    Route::resource('notaPembayarans', NotaPembayaranController::class)
        ->except(['create', 'store']);

    Route::get('suratJalans/create/{salesOrder}', [SuratJalanController::class, 'create'])
        ->name('suratJalans.create');

    Route::post('suratJalans/{salesOrder}', [SuratJalanController::class, 'store'])
        ->name('suratJalans.store');

    Route::resource('suratJalans', SuratJalanController::class)
        ->except(['create', 'store']);

    Route::patch('pemesananMaterials/confirm/{pemesananMaterial}', [PemesananMaterialController::class, 'confirm'])
        ->name('pemesananMaterials.confirm');

    Route::patch('pemesananMaterials/open/{pemesananMaterial}', [PemesananMaterialController::class, 'open'])
        ->name('pemesananMaterials.open');

    Route::resource('pemesananMaterials', PemesananMaterialController::class);

    Route::get('penerimaanMaterials/create/{pemesananMaterial}', [PenerimaanMaterialController::class, 'create'])
        ->name('penerimaanMaterials.create');

    Route::post('penerimaanMaterials/store/{pemesananMaterial}', [PenerimaanMaterialController::class, 'store'])
        ->name('penerimaanMaterials.store');

    Route::resource('penerimaanMaterials', PenerimaanMaterialController::class)
        ->except(['create', 'store']);

    Route::post('notaPelunasanSuppliers/store/{pemesananMaterial}', [NotaPelunasanSupplierController::class, 'store'])
        ->name('notaPelunasanSuppliers.store');

    Route::resource('notaPelunasanSuppliers', NotaPelunasanSupplierController::class)
        ->except(['create', 'store']);

    Route::resource('billOfMaterials', BillOfMaterialController::class);

    Route::resource('suratPerintahKerjas', SuratPerintahKerjaController::class);

    Route::get('permintaanMaterials/getBillOfMaterials/{id}', [PermintaanMaterialController::class, 'getBillOfMaterials']);

    Route::patch('permintaanMaterials/confirm/{permintaanMaterial}', [PermintaanMaterialController::class, 'confirm'])
        ->name('permintaanMaterials.confirm');
    
    Route::resource('permintaanMaterials', PermintaanMaterialController::class)
        ->except(['edit', 'update']);

    Route::get('perkiraanHpps/create/{billOfMaterial}', [PerkiraanHppController::class, 'create'])
        ->name('perkiraanHpps.create');

    Route::post('perkiraanHpps/store/{billOfMaterial}', [PerkiraanHppController::class, 'store'])
        ->name('perkiraanHpps.store');

    Route::resource('perkiraanHpps', PerkiraanHppController::class)
        ->except(['create', 'store']);

    Route::resource('realisasiProduksis', RealisasiProduksiController::class);

    Route::post('jurnals/find', [JurnalController::class, 'find'])
        ->name('jurnals.find');

    Route::get('jurnals/close', [JurnalController::class, 'close'])
        ->name('jurnals.close');

    Route::resource('jurnals', JurnalController::class)
        ->only(['index', 'create', 'store']);

    Route::get('bukuBesars', [BukuBesarController::class, 'index'])
        ->name('bukuBesars.index');

    Route::post('bukuBesars/find', [BukuBesarController::class, 'find'])
        ->name('bukuBesars.find');

    Route::get('laporanKeuangans', [LaporanKeuanganController::class, 'index'])
        ->name('laporanKeuangans.index');

    Route::post('laporanKeuangans/find', [LaporanKeuanganController::class, 'find'])
        ->name('laporanKeuangans.find');
});

app/Models/Divisi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Divisi extends Model
{
    use HasFactory;

    protected $fillable = [
        'nama_divisi',
    ];

    public function users()
    {
        return $this->hasMany(User::class);
    }
}

app/Http/Controllers/DivisiController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreDivisiRequest;
use App\Http\Requests\UpdateDivisiRequest;
use App\Models\Divisi;
use Illuminate\Support\Facades\Gate;

class DivisiController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('divisi access'), 403);

        $divisis = Divisi::all(['id', 'nama_divisi']);

        return view('divisi.index', compact('divisis'));
    }

    public function create()
    {
        abort_if(Gate::denies('divisi create'), 403);

        return view('divisi.create');
    }

    public function store(StoreDivisiRequest $request)
    {
        Divisi::create($request->validated());

        return redirect()
            ->route('divisis.index')
            ->with('success', 'Data divisi berhasil disimpan!');
    }

    public function edit(Divisi $divisi)
    {
        abort_if(Gate::denies('divisi edit'), 403);

        return view('divisi.edit', compact('divisi'));
    }

    public function update(UpdateDivisiRequest $request, Divisi $divisi)
    {
        $divisi->update($request->validated());

        return redirect()
            ->route('divisis.index')
            ->with('success', 'Data divisi berhasil diubah!');
    }

    public function destroy(Divisi $divisi)
    {
        abort_if(Gate::denies('divisi delete'), 403);

        if ($divisi->users()->exists()) {
            return redirect()
                ->route('divisis.index')
                ->with('error', 'Data divisi gagal dihapus!');
        }

        $divisi->delete();

        return redirect()
            ->route('divisis.index')
            ->with('success', 'Data divisi berhasil dihapus!');
    }
}

resources/views/divisi/create.blade.php
@extends('layouts.app')

@section('breadcrumb')
<div class="content-header-left col-12 mb-2 mt-1">
    <div class="breadcrumbs-top">
        <h5 class="content-header-title float-left pr-1 mb-0">Buat Divisi</h5>
        <div class="breadcrumb-wrapper d-none d-sm-block">
            <ol class="breadcrumb p-0 mb-0 pl-1">
                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}"><i class="bx bx-home-alt"></i></a>
                </li>
                <li class="breadcrumb-item active">Divisi
                </li>
            </ol>
        </div>
    </div>
</div>
@endsection

@section('content')
<section id="basic-vertical-layouts">
    <div class="row match-height">
        <div class="col-md-6 col-12">
            <div class="card">
                <form class="form form-vertical" action="{{ route('divisis.store') }}" method="post">
                    @csrf

                    <div class="card-body">                        
                        <div class="form-body">
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group">
                                        <label>Nama Divisi</label>
                                        <input type="text" aria-describedby="namaHelp" class="form-control @error('nama_divisi') is-invalid @enderror" name="nama_divisi" placeholder="Masukan Nama Divisi" value="{{ old('nama_divisi') }}">

                                        @error('nama_divisi')
                                            <small id="namaHelp" class="form-text text-danger">{{ $message}}</small>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row ">
                            <div class="col-6">
                                <button type="reset" class="btn btn-light-secondary">Reset</button>
                            </div>
                            <div class="col-6 d-flex justify-content-end">
                                <button type="submit" class="btn btn-primary">Simpan Data</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/divisi/edit.blade.php
@extends('layouts.app')

@section('breadcrumb')
<div class="content-header-left col-12 mb-2 mt-1">
    <div class="breadcrumbs-top">
        <h5 class="content-header-title float-left pr-1 mb-0">Ubah Divisi</h5>
        <div class="breadcrumb-wrapper d-none d-sm-block">
            <ol class="breadcrumb p-0 mb-0 pl-1">
                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}"><i class="bx bx-home-alt"></i></a>
                </li>
                <li class="breadcrumb-item active">Divisi
                </li>
            </ol>
        </div>
    </div>
</div>
@endsection

@section('content')
<section id="basic-vertical-layouts">
    <div class="row match-height">
        <div class="col-md-6 col-12">
            <div class="card">
                <form class="form form-vertical" action="{{ route('divisis.update', $divisi) }}" method="post">
                    @csrf
                    @method('patch')

                    <div class="card-body">                        
                        <div class="form-body">
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group">
                                        <label>Nama Divisi</label>
                                        <input type="text" aria-describedby="namaHelp" class="form-control @error('nama_divisi') is-invalid @enderror" name="nama_divisi" placeholder="Masukan Nama Divisi" value="{{ old('nama_divisi', $divisi->nama_divisi) }}">

                                        @error('nama_divisi')
                                            <small id="namaHelp" class="form-text text-danger">{{ $message}}</small>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row ">
                            <div class="col-6">
                                <button type="reset" class="btn btn-light-secondary">Reset</button>
                            </div>
                            <div class="col-6 d-flex justify-content-end">
                                <button type="submit" class="btn btn-warning">Ubah Data</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/divisi/index.blade.php
@extends('layouts.app')

@section('vendor css')
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/tables/datatable/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/tables/datatable/responsive.bootstrap4.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/tables/datatable/buttons.bootstrap4.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/extensions/toastr.css') }}">
@endsection

@section('page css')
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/plugins/extensions/toastr.css') }}">
@endsection

@section('breadcrumb')
<div class="content-header-left col-12 mb-2 mt-1">
    <div class="breadcrumbs-top">
        <h5 class="content-header-title float-left pr-1 mb-0">Divisi</h5>
        <div class="breadcrumb-wrapper d-none d-sm-block">
            <ol class="breadcrumb p-0 mb-0 pl-1">
                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}"><i class="bx bx-home-alt"></i></a>
                </li>
                <li class="breadcrumb-item active">Divisi
                </li>
            </ol>
        </div>
    </div>
</div>
@endsection

@section('content')
<section id="basic-datatable">
    @can('divisi create')
        <div class="invoice-create-btn mb-1">
            <a href="{{ route('divisis.create') }}" class="btn btn-primary btn-sm round glow align-items-center">Buat Divisi</a>
        </div>
    @endcan
    <div class="row">
        <div class="col-md-6 col-12">
            <div class="card">
                <div class="card-body card-dashboard">
                    <div class="table-responsive">
                        <table class="table zero-configuration">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>nama divisi</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($divisis as $divisi)
                                    <tr>
                                        <td>
                                            <small class="text-muted">{{ $loop->index +1 }}</small>
                                        </td>
                                        <td>
                                            <small class="text-muted">{{ $divisi->nama_divisi }}</small>
                                        </td>
                                        <td>
                                            <div class="invoice-action">
                                                @can('divisi edit')
                                                    <a href="{{ route('divisis.edit', $divisi) }}" class="invoice-action-edit mr-1">
                                                        <i class="bx bx-edit-alt"></i>
                                                    </a>
                                                @endcan

                                                @can('divisi delete')
                                                    <a href="#DeleteModal{{ $loop->index }}" data-toggle="modal" class="invoice-action-delete cursor-pointer">
                                                        <i class="bx bx-trash-alt"></i>
                                                    </a>
                                                @endcan
                                            </div>
                                        </td>
                                    </tr>

                                    {{-- BEGIN DELETE MODAL --}}
                                    <div class="modal fade text-left" id="DeleteModal{{ $loop->index }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel160" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                                            <div class="modal-content">
                                                <div class="modal-header bg-danger">
                                                    <h5 class="modal-title white" id="myModalLabel160">Hapus Data Divisi</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <i class="bx bx-x"></i>
                                                    </button>
                                                </div>
                                                <form action="{{ route('divisis.destroy', $divisi) }}" method="post">
                                                    @csrf
                                                    @method('delete')

                                                    <div class="modal-body">
                                                        <p>Apakah anda yakin untuk menghapus data tersebut?</p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-light-secondary" data-dismiss="modal">
                                                            <i class="bx bx-x d-block d-sm-none"></i>
                                                            <span class="d-none d-sm-block">Batal</span>
                                                        </button>
                                                        <button type="submit" class="btn btn-danger ml-1">
                                                            <i class="bx bx-check d-block d-sm-none"></i>
                                                            <span class="d-none d-sm-block">Hapus Data</span>
                                                        </button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                    {{-- END DELETE MODAL --}}
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@section('page vendor js')
<script src="{{ asset('app-assets/vendors/js/tables/datatable/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/tables/datatable/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/tables/datatable/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/tables/datatable/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/extensions/toastr.min.js') }}"></script>
@endsection

@section('page js')
<script src="{{ asset('app-assets/js/scripts/datatables/datatable.js') }}"></script>
@endsection

@section('script')
<script type="text/javascript">
    @if(Session::has('success'))
        toastr['success']("{{ session('success') }}", {
            tapToDismiss: true,
        });
    @endif

    @if(Session::has('error'))
        toastr['error']("{{ session('error') }}", {
            tapToDismiss: true,
        });
    @endif
</script>
@endsection