routes/web.php
<?php

use App\Http\Controllers\{
    AkunController,
    BatalOrderController,
    BillOfMaterialController,
    BukuBesarController,
    DashboardController,
    DivisiController,
    JabatanController,
    JurnalController,
    LaporanKeuanganController,
    OtorisasiController,
    PasswordController,
    PelangganController,
    PemesananMaterialController,
    PenerimaanMaterialController,
    ProdukController,
    ProfileController,
    SalesOrderController,
    SupplierController,
    SuratJalanController,
    SuratPerintahKerjaController,
    UserController,
    NotaPelunasanSupplierController,
    NotaPembayaranController,
    PerkiraanHppController,
    PermintaanMaterialController,
    RealisasiProduksiController,
};
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'verify'   => false,
]);

Route::middleware('auth')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])
        ->name('dashboard');

    Route::post('markNotification', [DashboardController::class, 'markNotification'])
        ->name('markNotification');

    Route::resource('divisis', DivisiController::class)
        ->except(['show']);

    Route::resource('jabatans', JabatanController::class)
        ->except('show');

    Route::resource('users', UserController::class)
        ->except(['show', 'destroy']);

    Route::resource('pelanggans', PelangganController::class)
        ->except(['show']);

    Route::resource('suppliers', SupplierController::class)
        ->except(['show']);

    Route::get('otorisasis', [OtorisasiController::class, 'index'])
        ->name('otorisasis.index');

    Route::resource('produks', ProdukController::class)
        ->except(['show', 'destroy']);

    Route::get('akuns', [AkunController::class, 'index'])
        ->name('akuns.index');

    Route::prefix('profile')->group(function () {
        Route::get('/{user}', [ProfileController::class, 'edit'])
            ->name('profile.edit');

        Route::patch('/{user}', [ProfileController::class, 'update'])
            ->name('profile.update');

        Route::patch('/passwordUpdate/{user}', [PasswordController::class, 'update'])
            ->name('password.update');
    });

    Route::patch('salesOrders/{salesOrder}/confirm', [SalesOrderController::class, 'confirm'])
        ->name('salesOrders.confirm');

    Route::resource('salesOrders', SalesOrderController::class);

    Route::post('batalOrders/{salesOrder}', [BatalOrderController::class, 'store'])
            ->name('batalOrders.store');

    Route::resource('batalOrders', BatalOrderController::class)
        ->except(['create', 'store', 'show', 'destroy']);

    Route::post('notaPembayarans/{salesOrder}', [NotaPembayaranController::class, 'store'])
        ->name('notaPembayarans.store');

    Route::resource('notaPembayarans', NotaPembayaranController::class)
        ->except(['create', 'store']);

    Route::get('suratJalans/create/{salesOrder}', [SuratJalanController::class, 'create'])
        ->name('suratJalans.create');

    Route::post('suratJalans/{salesOrder}', [SuratJalanController::class, 'store'])
        ->name('suratJalans.store');

    Route::resource('suratJalans', SuratJalanController::class)
        ->except(['create', 'store']);

    Route::patch('pemesananMaterials/confirm/{pemesananMaterial}', [PemesananMaterialController::class, 'confirm'])
        ->name('pemesananMaterials.confirm');

    Route::patch('pemesananMaterials/open/{pemesananMaterial}', [PemesananMaterialController::class, 'open'])
        ->name('pemesananMaterials.open');

    Route::resource('pemesananMaterials', PemesananMaterialController::class);

    Route::get('penerimaanMaterials/create/{pemesananMaterial}', [PenerimaanMaterialController::class, 'create'])
        ->name('penerimaanMaterials.create');

    Route::post('penerimaanMaterials/store/{pemesananMaterial}', [PenerimaanMaterialController::class, 'store'])
        ->name('penerimaanMaterials.store');

    Route::resource('penerimaanMaterials', PenerimaanMaterialController::class)
        ->except(['create', 'store']);

    Route::post('notaPelunasanSuppliers/store/{pemesananMaterial}', [NotaPelunasanSupplierController::class, 'store'])
        ->name('notaPelunasanSuppliers.store');

    Route::resource('notaPelunasanSuppliers', NotaPelunasanSupplierController::class)
        ->except(['create', 'store']);

    Route::resource('billOfMaterials', BillOfMaterialController::class);

    Route::resource('suratPerintahKerjas', SuratPerintahKerjaController::class);

    Route::get('permintaanMaterials/getBillOfMaterials/{id}', [PermintaanMaterialController::class, 'getBillOfMaterials']);

    Route::patch('permintaanMaterials/confirm/{permintaanMaterial}', [PermintaanMaterialController::class, 'confirm'])
        ->name('permintaanMaterials.confirm');
    
    Route::resource('permintaanMaterials', PermintaanMaterialController::class)
        ->except(['edit', 'update']);

    Route::get('perkiraanHpps/create/{billOfMaterial}', [PerkiraanHppController::class, 'create'])
        ->name('perkiraanHpps.create');

    Route::post('perkiraanHpps/store/{billOfMaterial}', [PerkiraanHppController::class, 'store'])
        ->name('perkiraanHpps.store');

    Route::resource('perkiraanHpps', PerkiraanHppController::class)
        ->except(['create', 'store']);

    Route::resource('realisasiProduksis', RealisasiProduksiController::class);

    Route::post('jurnals/find', [JurnalController::class, 'find'])
        ->name('jurnals.find');

    Route::get('jurnals/close', [JurnalController::class, 'close'])
        ->name('jurnals.close');

    Route::resource('jurnals', JurnalController::class)
        ->only(['index', 'create', 'store']);

    Route::get('bukuBesars', [BukuBesarController::class, 'index'])
        ->name('bukuBesars.index');

    Route::post('bukuBesars/find', [BukuBesarController::class, 'find'])
        ->name('bukuBesars.find');

    Route::get('laporanKeuangans', [LaporanKeuanganController::class, 'index'])
        ->name('laporanKeuangans.index');

    Route::post('laporanKeuangans/find', [LaporanKeuanganController::class, 'find'])
        ->name('laporanKeuangans.find');
});

app/Models/Supplier.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    use HasFactory;

    protected $fillable = [
        'nama_supplier',
        'alamat_supplier',
        'kota_supplier',
        'email_supplier',
        'no_telepon',
    ];

    public function pemesananMaterials()
    {
        return $this->hasMany(PemesananMaterial::class);
    }
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreSupplierRequest;
use App\Http\Requests\UpdateSupplierRequest;
use App\Models\Supplier;
use Illuminate\Support\Facades\Gate;

class SupplierController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('supplier access'), 403);

        $suppliers = Supplier::all();

        return view('supplier.index', compact('suppliers'));
    }

    public function create()
    {
        abort_if(Gate::denies('supplier create'), 403);

        return view('supplier.create');
    }

    public function store(StoreSupplierRequest $request)
    {
        Supplier::create($request->validated());

        return redirect()
            ->route('suppliers.index')
            ->with('success', 'Data supplier berhasil disimpan!');
    }

    public function edit(Supplier $supplier)
    {
        abort_if(Gate::denies('supplier edit'), 403);

        return view('supplier.edit', compact('supplier'));
    }

    public function update(UpdateSupplierRequest $request, Supplier $supplier)
    {
        $supplier->update($request->validated());

        return redirect()
            ->route('suppliers.index')
            ->with('success', 'Data supplier berhasil diubah!');
    }

    public function destroy(Supplier $supplier)
    {
        abort_if(Gate::denies('supplier delete'), 403);

        if ($supplier->pemesananMaterials()->exists()) {
            return redirect()
                ->route('suppliers.index')
                ->with('error', 'Data supplier gagal dihapus!');
        }

        $supplier->delete();

        return redirect()
            ->route('suppliers.index')
            ->with('success', 'Data supplier berhasil dihapus!');
    }
}

resources/views/supplier/create.blade.php
@extends('layouts.app')

@section('breadcrumb')
<div class="content-header-left col-12 mb-2 mt-1">
    <div class="breadcrumbs-top">
        <h5 class="content-header-title float-left pr-1 mb-0">Buat Supplier</h5>
        <div class="breadcrumb-wrapper d-none d-sm-block">
            <ol class="breadcrumb p-0 mb-0 pl-1">
                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}"><i class="bx bx-home-alt"></i></a>
                </li>
                <li class="breadcrumb-item active">Supplier
                </li>
            </ol>
        </div>
    </div>
</div>
@endsection

@section('content')
<section id="multiple-column-form">
    <div class="row match-height">
        <div class="col-12 col-md-8">
            <div class="card">
                <form class="form" action="{{ route('suppliers.store') }}" method="post">
                    @csrf
                    
                    <div class="card-body">
                        <div class="form-body">
                            <div class="row">
                                <div class="col-md-6 col-12">
                                    <div class="form-group">
                                        <label>Nama Supplier</label>
                                        <input type="text" aria-describedby="namaHelp" class="form-control @error('nama_supplier') is-invalid @enderror" name="nama_supplier" placeholder="Masukan Nama Supplier" value="{{ old('nama_supplier') }}">

                                        @error('nama_supplier')
                                            <small id="namaHelp" class="form-text text-danger">{{ $message}}</small>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-6 col-12">
                                    <div class="form-group">
                                        <label>Email Supplier (Opsional)</label>
                                        <input type="email" aria-describedby="emailHelp" class="form-control @error('email_supplier') is-invalid @enderror" name="email_supplier" placeholder="Masukan Email Supplier (Opsional)" value="{{ old('email_supplier') }}">

                                        @error('email_supplier')
                                            <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-6 col-12">
                                    <div class="form-group">
                                        <label>Alamat Supplier</label>
                                        <input type="text" aria-describedby="alamatHelp" class="form-control @error('alamat_supplier') is-invalid @enderror" name="alamat_supplier" placeholder="Masukan Alamat Supplier" value="{{ old('alamat_supplier') }}">

                                        @error('alamat_supplier')
                                            <small id="alamatHelp" class="form-text text-danger">{{ $message }}</small>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-6 col-12">
                                    <div class="form-group">
                                        <label>Kota Supplier</label>
                                        <input type="text" aria-describedby="kotaHelp" class="form-control @error('kota_supplier') is-invalid @enderror" name="kota_supplier" placeholder="Masukan Kota Supplier" value="{{ old('kota_supplier') }}">

                                        @error('kota_supplier')
                                            <small id="kotaHelp" class="form-text text-danger">{{ $message }}</small>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-6 col-12">
                                    <div class="form-group">
                                        <label>Nomor Telepon</label>
                                        <input type="tel" aria-describedby="telpHelp" class="form-control @error('no_telepon') is-invalid @enderror" name="no_telepon" placeholder="Contoh: 081233911680" value="{{ old('no_telepon') }}">

                                        @error('no_telepon')
                                            <small id="telpHelp" class="form-text text-danger">{{ $message }}</small>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row ">
                            <div class="col-6">
                                <button type="reset" class="btn btn-light-secondary">Reset</button>
                            </div>
                            <div class="col-6 d-flex justify-content-end">
                                <button type="submit" class="btn btn-primary">Simpan Data</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/supplier/edit.blade.php
@extends('layouts.app')

@section('breadcrumb')
<div class="content-header-left col-12 mb-2 mt-1">
    <div class="breadcrumbs-top">
        <h5 class="content-header-title float-left pr-1 mb-0">Ubah Supplier</h5>
        <div class="breadcrumb-wrapper d-none d-sm-block">
            <ol class="breadcrumb p-0 mb-0 pl-1">
                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}"><i class="bx bx-home-alt"></i></a>
                </li>
                <li class="breadcrumb-item active">Supplier
                </li>
            </ol>
        </div>
    </div>
</div>
@endsection

@section('content')
<section id="multiple-column-form">
    <div class="row match-height">
        <div class="col-12 col-md-8">
            <div class="card">
                <form class="form" action="{{ route('suppliers.update', $supplier) }}" method="post">
                    @csrf
                    @method('patch')
                    
                    <div class="card-body">
                        <div class="form-body">
                            <div class="row">
                                <div class="col-md-6 col-12">
                                    <div class="form-group">
                                        <label>Nama Supplier</label>
                                        <input type="text" aria-describedby="namaHelp" class="form-control @error('nama_supplier') is-invalid @enderror" name="nama_supplier" placeholder="Masukan Nama Supplier" value="{{ old('nama_supplier', $supplier->nama_supplier) }}">

                                        @error('nama_supplier')
                                            <small id="namaHelp" class="form-text text-danger">{{ $message}}</small>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-6 col-12">
                                    <div class="form-group">
                                        <label>Email Supplier (Opsional)</label>
                                        <input type="email" aria-describedby="emailHelp" class="form-control @error('email_supplier') is-invalid @enderror" name="email_supplier" placeholder="Masukan Email Supplier (Opsional)" value="{{ old('email_supplier', $supplier->email_supplier) }}">

                                        @error('email_supplier')
                                            <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-6 col-12">
                                    <div class="form-group">
                                        <label>Alamat Supplier</label>
                                        <input type="text" aria-describedby="alamatHelp" class="form-control @error('alamat_supplier') is-invalid @enderror" name="alamat_supplier" placeholder="Masukan Alamat Supplier" value="{{ old('alamat_supplier', $supplier->alamat_supplier) }}">

                                        @error('alamat_supplier')
                                            <small id="alamatHelp" class="form-text text-danger">{{ $message }}</small>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-6 col-12">
                                    <div class="form-group">
                                        <label>Kota Supplier</label>
                                        <input type="text" aria-describedby="kotaHelp" class="form-control @error('kota_supplier') is-invalid @enderror" name="kota_supplier" placeholder="Masukan Kota Supplier" value="{{ old('kota_supplier', $supplier->kota_supplier) }}">

                                        @error('kota_supplier')
                                            <small id="kotaHelp" class="form-text text-danger">{{ $message }}</small>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-6 col-12">
                                    <div class="form-group">
                                        <label>Nomor Telepon</label>
                                        <input type="tel" aria-describedby="telpHelp" class="form-control @error('no_telepon') is-invalid @enderror" name="no_telepon" placeholder="Contoh: 081233911680" value="{{ old('no_telepon', $supplier->no_telepon) }}">

                                        @error('no_telepon')
                                            <small id="telpHelp" class="form-text text-danger">{{ $message }}</small>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row ">
                            <div class="col-6">
                                <button type="reset" class="btn btn-light-secondary">Reset</button>
                            </div>
                            <div class="col-6 d-flex justify-content-end">
                                <button type="submit" class="btn btn-warning">Ubah Data</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/supplier/index.blade.php
@extends('layouts.app')

@section('vendor css')
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/tables/datatable/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/tables/datatable/responsive.bootstrap4.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/tables/datatable/buttons.bootstrap4.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/extensions/toastr.css') }}">
@endsection

@section('page css')
<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/plugins/extensions/toastr.css') }}">
@endsection

@section('breadcrumb')
<div class="content-header-left col-12 mb-2 mt-1">
    <div class="breadcrumbs-top">
        <h5 class="content-header-title float-left pr-1 mb-0">Supplier</h5>
        <div class="breadcrumb-wrapper d-none d-sm-block">
            <ol class="breadcrumb p-0 mb-0 pl-1">
                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}"><i class="bx bx-home-alt"></i></a>
                </li>
                <li class="breadcrumb-item active">Supplier
                </li>
            </ol>
        </div>
    </div>
</div>
@endsection

@section('content')
<section id="basic-datatable">
    @can('supplier create')
        <div class="invoice-create-btn mb-1">
            <a href="{{ route('suppliers.create') }}" class="btn btn-primary btn-sm round glow align-items-center">Buat Supplier</a>
        </div>
    @endcan
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body card-dashboard">
                    <div class="table-responsive">
                        <table class="table zero-configuration">
                            <thead>
                                <tr>
                                    <th>nama</th>
                                    <th>alamat</th>
                                    <th>kota</th>
                                    <th>email</th>
                                    <th>telp</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($suppliers as $supplier)
                                    <tr>
                                        <td>
                                            <small class="text-muted">{{ $supplier->nama_supplier }}</small>
                                        </td>
                                        <td>
                                            <small class="text-muted">{{ $supplier->alamat_supplier }}</small>
                                        </td>
                                        <td>
                                            <small class="text-muted">{{ $supplier->kota_supplier }}</small>
                                        </td>
                                        <td>
                                            @switch($supplier->email_supplier)
                                                @case(null)
                                                    <span class="badge badge-light-info badge-pill">not found</span>
                                                    @break
                                                @default
                                                    <small class="text-muted">{{ $supplier->email_supplier }}</small>
                                            @endswitch
                                        </td>
                                        <td>
                                            <small class="text-muted">{{ $supplier->no_telepon }}</small>
                                        </td>
                                        <td>
                                            <div class="invoice-action">
                                                @can('supplier edit')
                                                    <a href="{{ route('suppliers.edit', $supplier) }}" class="invoice-action-edit mr-1">
                                                        <i class="bx bx-edit-alt"></i>
                                                    </a>
                                                @endcan

                                                @can('supplier delete')
                                                    <a href="#DeleteModal{{ $loop->index }}" data-toggle="modal" class="invoice-action-delete cursor-pointer">
                                                        <i class="bx bx-trash-alt"></i>
                                                    </a>
                                                @endcan
                                            </div>
                                        </td>
                                    </tr>

                                    {{-- BEGIN DELETE MODAL --}}
                                    <div class="modal fade text-left" id="DeleteModal{{ $loop->index }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel160" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                                            <div class="modal-content">
                                                <div class="modal-header bg-danger">
                                                    <h5 class="modal-title white" id="myModalLabel160">Hapus Data Supplier</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <i class="bx bx-x"></i>
                                                    </button>
                                                </div>
                                                <form action="{{ route('suppliers.destroy', $supplier) }}" method="post">
                                                    @csrf
                                                    @method('delete')

                                                    <div class="modal-body">
                                                        <p>Apakah anda yakin untuk menghapus data tersebut?</p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-light-secondary" data-dismiss="modal">
                                                            <i class="bx bx-x d-block d-sm-none"></i>
                                                            <span class="d-none d-sm-block">Batal</span>
                                                        </button>
                                                        <button type="submit" class="btn btn-danger ml-1">
                                                            <i class="bx bx-check d-block d-sm-none"></i>
                                                            <span class="d-none d-sm-block">Hapus Data</span>
                                                        </button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                    {{-- END DELETE MODAL --}}
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@section('page vendor js')
<script src="{{ asset('app-assets/vendors/js/tables/datatable/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/tables/datatable/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/tables/datatable/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/tables/datatable/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/extensions/toastr.min.js') }}"></script>
@endsection

@section('page js')
<script src="{{ asset('app-assets/js/scripts/datatables/datatable.js') }}"></script>
@endsection

@section('script')
<script type="text/javascript">
    @if(Session::has('success'))
        toastr['success']("{{ session('success') }}", {
            tapToDismiss: true,
        });
    @endif

    @if(Session::has('error'))
        toastr['error']("{{ session('error') }}", {
            tapToDismiss: true,
        });
    @endif
</script>
@endsection